In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [2]:
df = pd.read_csv("data.csv")

In [3]:
print(df.head())
print(df.tail())

   Id Colour Country
0   1    Red     USA
1   2   Blue      UK
2   3  Green  Canada
3   4   Blue     USA
4   5   Blue     USA
      Id Colour Country
295  296    Red  Canada
296  297  Green      UK
297  298  Green      UK
298  299    Red  Canada
299  300    Red  Canada


In [4]:
df.dtypes

Id          int64
Colour     object
Country    object
dtype: object

In [5]:
print(df['Country'].unique())
print(df['Colour'].unique())

['USA' 'UK' 'Canada']
['Red' 'Blue' 'Green']


In [6]:
print(df['Country'].value_counts())
print(df['Colour'].value_counts())

Country
Canada    120
USA        90
UK         90
Name: count, dtype: int64
Colour
Red      120
Blue      90
Green     90
Name: count, dtype: int64


In [7]:
ohe = OneHotEncoder()

In [8]:
print(ohe.fit_transform(df[["Colour" , "Country"]]).toarray)
print(ohe.fit_transform(df[["Colour" , "Country"]]).toarray())

<bound method _cs_matrix.toarray of <Compressed Sparse Row sparse matrix of dtype 'float64'
	with 600 stored elements and shape (300, 6)>>
[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]]


In [9]:
feature_array = ohe.fit_transform(df[["Colour" , "Country"]]).toarray()

In [10]:
ohe.categories_
feature_labels = ohe.categories_

In [15]:
feature_labels = np.array(feature_labels).ravel()

In [12]:
feature_array

array([[0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.]])

In [13]:
feature_labels

[array(['Blue', 'Green', 'Red'], dtype=object),
 array(['Canada', 'UK', 'USA'], dtype=object)]

In [16]:
pd.DataFrame(feature_array, columns=feature_labels)

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     1.0    0.0  0.0     0.0  1.0  0.0
2     0.0    1.0  0.0     1.0  0.0  0.0
3     1.0    0.0  0.0     0.0  0.0  1.0
4     1.0    0.0  0.0     0.0  0.0  1.0
..    ...    ...  ...     ...  ...  ...
295   0.0    0.0  1.0     1.0  0.0  0.0
296   0.0    1.0  0.0     0.0  1.0  0.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    0.0  1.0     1.0  0.0  0.0
299   0.0    0.0  1.0     1.0  0.0  0.0

[300 rows x 6 columns]